const rooms={Bedroom:['bed','pillow','wardrobe','lamp','mirror','carpet'],Living:['sofa','armchair','table','TV','bookshelf','picture'],Kitchen:['fridge','cooker','oven','kettle','sink','cupboard'],Bathroom:['bath','shower','sink','mirror','towel','soap'],Hall:['door','coat','mirror','shoes','bag','keys'],Dining:['table','chair','plate','glass','fork','spoon']};
const words=[['bed','/bed/','кровать'],['pillow','/ˈpɪləʊ/','подушка'],['wardrobe','/ˈwɔːdrəʊb/','шкаф'],['lamp','/læmp/','лампа'],['mirror','/ˈmɪrə/','зеркало'],['sofa','/ˈsəʊfə/','диван'],['chair','/tʃeə/','стул'],['table','/ˈteɪbəl/','стол'],['window','/ˈwɪndəʊ/','окно'],['door','/dɔː/','дверь'],['fridge','/frɪdʒ/','холодильник'],['kettle','/ˈketəl/','чайник'],['shower','/ˈʃaʊə/','душ'],['towel','/ˈtaʊəl/','полотенце'],['carpet','/ˈkɑːpɪt/','ковёр'],['picture','/ˈpɪktʃə/','картина']];
let state=JSON.parse(localStorage.getItem('osdProgress')||'{"xp":0,"correct":0,"streak":0,"best":0,"wins":0,"seen":[]}');
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('osdProgress',JSON.stringify(state));renderProgress()}
function reward(x=10){state.xp+=x;state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);save()}
function miss(){state.streak=0;save()}
function speak(text){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.82;let vs=speechSynthesis.getVoices();let v=vs.find(v=>v.lang==='en-GB')||vs.find(v=>v.lang.startsWith('en'));if(v)u.voice=v;speechSynthesis.speak(u)}
function toast(ok,msg){const t=$('#characterToast');t.innerHTML=ok?`<strong>👍 Mike:</strong><br>${msg||'Alice, good job! You’re amazing!'}`:`<strong>👹 Demogorgon:</strong><br>${msg||'No, not right. Try again!'}`;t.classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.add('hidden'),2600)}
$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
function renderRooms(){let keys=Object.keys(rooms);$('#roomButtons').innerHTML=keys.map((r,i)=>`<button class="${i?'':'active'}" data-room="${r}">${r}</button>`).join('');$$('[data-room]').forEach(b=>b.onclick=()=>{ $$('[data-room]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showRoom(b.dataset.room)});showRoom(keys[0])}
function showRoom(r){$('#roomPanel').innerHTML=`<div><p class="eyebrow">HAWKINS HOUSE</p><h3>${r}</h3><p>Нажимай на предметы и слушай их произношение.</p></div><div class="room-words">${rooms[r].map(w=>`<button class="room-word" data-say="${w}">🔊 ${w}</button>`).join('')}</div>`;$$('.room-word').forEach(b=>b.onclick=()=>{speak(b.dataset.say);if(!state.seen.includes(b.dataset.say)){state.seen.push(b.dataset.say);state.xp+=2;save()}})}
function renderWords(){ $('#wordGrid').innerHTML=words.map(w=>`<article class="word-card"><h3>${w[0]}</h3><p>${w[1]}</p><p>${w[2]}</p><button data-word="${w[0]}">🔊 Listen</button></article>`).join('');$$('[data-word]').forEach(b=>b.onclick=()=>{speak(b.dataset.word);if(!state.seen.includes(b.dataset.word)){state.seen.push(b.dataset.word);state.xp+=2;save()}})}
let listenWord='window';function newListen(){listenWord=words[Math.floor(Math.random()*words.length)][0];let opts=[listenWord];while(opts.length<3){let w=words[Math.floor(Math.random()*words.length)][0];if(!opts.includes(w))opts.push(w)}opts.sort(()=>Math.random()-.5);$('#listenOptions').innerHTML=opts.map(w=>`<button>${w}</button>`).join('');$('#listenOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.textContent===listenWord){reward();toast(true,'Good job, Alice! Great listening!');$('#listenFeedback').textContent='✓ Правильно!';setTimeout(newListen,800)}else{miss();toast(false,'No, not right. Listen one more time.');$('#listenFeedback').textContent='Попробуй ещё раз.'}})}$('#listenPlay').onclick=()=>speak(listenWord);
let built='';const target='window';function initRead(){let letters=['w','i','n','d','o','w'].sort(()=>Math.random()-.5);$('#letterPool').innerHTML=letters.map((l,i)=>`<button data-letter="${l}" data-i="${i}">${l}</button>`).join('');$$('[data-letter]').forEach(b=>b.onclick=()=>{built+=b.dataset.letter;b.disabled=true;$('#builtWord').textContent=built});}$('#clearWord').onclick=()=>{built='';$('#builtWord').textContent='_ _ _ _ _ _';initRead()};$('#checkWord').onclick=()=>{if(built===target){reward(15);speak('window');toast(true,'Alice, you did it! Beautiful work!');$('#readFeedback').textContent='✓ window /ˈwɪndəʊ/ — окно'}else{miss();toast(false,'Not this time. Look at the letters again!');$('#readFeedback').textContent='Пока не получилось. Попробуй ещё.'}};
const thereQs=[['___ a lamp on the desk.','There is'],['___ two books on the table.','There are'],['___ a window in the bedroom.','There is'],['___ three chairs in the dining room.','There are']];let tq=0;function there(){let q=thereQs[tq%thereQs.length];$('#thereExercise').innerHTML=`<h3>${q[0]}</h3><div class="answer-grid"><button>There is</button><button>There are</button></div><div class="feedback"></div>`;$('#thereExercise').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.textContent===q[1]){reward();toast(true,'Good job! You know the Hawkins rule!');tq++;setTimeout(there,700)}else{miss();toast(false,'No, not right. Один предмет — IS, несколько — ARE.')}})}
['in','on','under','next to'].forEach(p=>{let b=document.createElement('button');b.textContent=p;b.onclick=()=>{if(p==='under'){reward();toast(true,'Exactly, Alice! The ball is under the table.');$('#prepFeedback').textContent='✓ The ball is under the table.'}else{miss();toast(false,'Look carefully. Where is the ball?')}};$('#prepOptions').appendChild(b)});
let sent=[];const sentence=['There','is','a','cat','on','the','bed.'];function initSentence(){let mix=[...sentence].sort(()=>Math.random()-.5);$('#sentencePool').innerHTML=mix.map((w,i)=>`<button data-s="${w}" data-si="${i}">${w}</button>`).join('');$$('[data-s]').forEach(b=>b.onclick=()=>{sent.push(b.dataset.s);b.disabled=true;$('#sentenceBuilt').textContent=sent.join(' ')})}$('#resetSentence').onclick=()=>{sent=[];$('#sentenceBuilt').textContent='';initSentence()};$('#checkSentence').onclick=()=>{if(sent.join(' ')===sentence.join(' ')){reward(15);speak(sentence.join(' '));toast(true,'Alice, perfect sentence! Good job!');$('#sentenceFeedback').textContent='✓ Всё правильно!'}else{miss();toast(false,'Almost! Check the word order.');$('#sentenceFeedback').textContent='Проверь порядок слов.'}};
const battle=[['Choose the correct sentence.',['There is a sofa.','There are a sofa.'],0],['Two books: choose correctly.',['There is two books.','There are two books.'],1],['The ball is ___ the table.',['under','between'],0],['Which means «окно»?',['window','wall'],0],['Listen and choose.',['chair','shower'],0]];let bi=0,health=100;function battleQ(){let q=battle[bi%battle.length];$('#battleQuestion').textContent=q[0];$('#battleOptions').innerHTML=q[1].map((x,i)=>`<button data-bi="${i}">${x}</button>`).join('');$('#nextBattle').classList.add('hidden');$$('[data-bi]').forEach(b=>b.onclick=()=>{if(+b.dataset.bi===q[2]){reward(20);health-=25;$('#demoHealth').style.width=Math.max(0,health)+'%';toast(true,'Great hit, Alice! You’re so smart!');$('#battleFeedback').textContent='⚡ Попадание!';if(health<=0){state.wins++;state.xp+=50;save();$('#battleFeedback').textContent='🏆 Демогоргон побеждён!';health=100}bi++;$('#nextBattle').classList.remove('hidden')}else{miss();toast(false,'No, not right! I’m still here!');$('#battleFeedback').textContent='Демогоргон увернулся. Есть ещё попытка!'}})}$('#nextBattle').onclick=battleQ;
function renderProgress(){$('#xpValue').textContent=state.xp;$('#correctCount').textContent=state.correct;$('#streakCount').textContent=state.best;$('#battleWins').textContent=state.wins;$('#wordsSeen').textContent=state.seen.length}
renderRooms();renderWords();newListen();initRead();there();initSentence();battleQ();renderProgress();
