const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
let state=JSON.parse(localStorage.getItem('osdProgressV2')||'{"xp":0,"correct":0,"best":0,"streak":0,"wins":0,"known":[],"repeat":[],"practice":0}');
function save(){localStorage.setItem('osdProgressV2',JSON.stringify(state));paintProgress()}
function speak(text){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.82;const vv=speechSynthesis.getVoices();u.voice=vv.find(v=>v.lang==='en-GB')||vv.find(v=>v.lang.startsWith('en'))||null;speechSynthesis.speak(u)}
function reward(x=10){state.xp+=x;state.correct++;state.practice++;state.streak++;state.best=Math.max(state.best,state.streak);save()}
function miss(){state.streak=0;save()}
function character(ok,msg){let p=qs('#characterPopup');if(!p){p=document.createElement('div');p.id='characterPopup';p.className='character-popup hidden';document.body.appendChild(p)}p.innerHTML=`<img src="assets/${ok?'mike':'demogorgon'}.svg" alt="${ok?'Mike':'Demogorgon'}"><div class="speech-bubble"><b>${ok?'Mike':'Demogorgon'}</b><p>${msg}</p></div>`;p.classList.remove('hidden');clearTimeout(window._cp);window._cp=setTimeout(()=>p.classList.add('hidden'),3200)}
function navActive(){const f=location.pathname.split('/').pop()||'index.html';qsa('.side-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===f))}
function paintProgress(){qsa('[data-xp]').forEach(e=>e.textContent=state.xp);qsa('[data-correct]').forEach(e=>e.textContent=state.correct);qsa('[data-best]').forEach(e=>e.textContent=state.best);qsa('[data-known]').forEach(e=>e.textContent=state.known.length);qsa('[data-repeat]').forEach(e=>e.textContent=state.repeat.length);qsa('[data-wins]').forEach(e=>e.textContent=state.wins);const pct=Math.min(100,Math.round((state.known.length/40)*100));qsa('[data-progress]').forEach(e=>e.textContent=pct+'%');qsa('.progress-ring').forEach(e=>e.style.setProperty('--p',pct))}

const vocab=[
{w:'bed',ipa:'/bed/',ru:'кровать',ex:'There is a bed in the bedroom.',exipa:'/ðeər ɪz ə bed ɪn ðə ˈbedruːm/',exru:'В спальне есть кровать.'},
{w:'lamp',ipa:'/læmp/',ru:'лампа',ex:'There is a lamp on the desk.',exipa:'/ðeər ɪz ə læmp ɒn ðə desk/',exru:'На письменном столе есть лампа.'},
{w:'wardrobe',ipa:'/ˈwɔːdrəʊb/',ru:'шкаф',ex:'The wardrobe is next to the bed.',exipa:'/ðə ˈwɔːdrəʊb ɪz nekst tə ðə bed/',exru:'Шкаф находится рядом с кроватью.'},
{w:'window',ipa:'/ˈwɪndəʊ/',ru:'окно',ex:'There is a window in the room.',exipa:'/ðeər ɪz ə ˈwɪndəʊ ɪn ðə ruːm/',exru:'В комнате есть окно.'},
{w:'armchair',ipa:'/ˈɑːmtʃeə/',ru:'кресло',ex:'There is an armchair in the living room.',exipa:'/ðeər ɪz ən ˈɑːmtʃeər ɪn ðə ˈlɪvɪŋ ruːm/',exru:'В гостиной есть кресло.'},
{w:'bookshelf',ipa:'/ˈbʊkʃelf/',ru:'книжная полка',ex:'There are books on the bookshelf.',exipa:'/ðeər ɑː bʊks ɒn ðə ˈbʊkʃelf/',exru:'На книжной полке есть книги.'},
{w:'mirror',ipa:'/ˈmɪrə/',ru:'зеркало',ex:'The mirror is above the sink.',exipa:'/ðə ˈmɪrər ɪz əˈbʌv ðə sɪŋk/',exru:'Зеркало находится над раковиной.'},
{w:'kettle',ipa:'/ˈketəl/',ru:'чайник',ex:'The kettle is in the kitchen.',exipa:'/ðə ˈketəl ɪz ɪn ðə ˈkɪtʃɪn/',exru:'Чайник находится на кухне.'}
];

function initFlashcards(){const card=qs('#studyCard');if(!card)return;let i=0;function show(){const v=vocab[i%vocab.length];card.innerHTML=`<span class="card-count">${i%vocab.length+1} / ${vocab.length}</span><h2>${v.w}</h2><div class="ipa">${v.ipa}</div><div class="translation">${v.ru}</div><button class="listen-btn">LISTEN</button><div class="example-line"><b>${v.ex}</b><span>${v.exipa}</span><em>${v.exru}</em></div>`;qs('.listen-btn',card).onclick=()=>speak(v.w);qs('#knownBtn').onclick=()=>{if(!state.known.includes(v.w))state.known.push(v.w);state.repeat=state.repeat.filter(x=>x!==v.w);reward(5);character(true,'Alice, you’re amazing! Это слово уже твоё.');i++;show()};qs('#repeatBtn').onclick=()=>{if(!state.repeat.includes(v.w))state.repeat.push(v.w);state.known=state.known.filter(x=>x!==v.w);save();character(false,'Попробуем ещё раз позже. Я запомнил это слово для повторения.');i++;show()};qs('#nextCard').onclick=()=>{i++;show()};qs('#prevCard').onclick=()=>{i=(i-1+vocab.length)%vocab.length;show()}}show()}

function initDrag(){const bank=qs('#wordBank');if(!bank)return;const items=[['book','a'],['lamp','a'],['apple','an'],['armchair','an'],['water','none'],['air','none'],['hour','an'],['school','a']];bank.innerHTML=items.map(([w,c])=>`<div class="drag-word" draggable="true" data-cat="${c}" data-word="${w}">${w}<button aria-label="listen">♪</button></div>`).join('');qsa('.drag-word').forEach(el=>{el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.word));qs('button',el).onclick=e=>{e.stopPropagation();speak(el.dataset.word)};el.onclick=()=>el.classList.toggle('selected')});qsa('.drop-zone').forEach(z=>{z.addEventListener('dragover',e=>e.preventDefault());z.addEventListener('drop',e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),z)});z.onclick=()=>{const s=qs('.drag-word.selected');if(s)place(s.dataset.word,z)}});function place(word,z){const el=qsa('.drag-word').find(x=>x.dataset.word===word);if(!el)return;if(el.dataset.cat===z.dataset.cat){z.appendChild(el);el.classList.remove('selected');reward(8);character(true,'Good job, Alice! Perfect choice!')}else{miss();character(false,'No, not right. Подумай о первом звуке слова и попробуй снова.')}}}

function initRuleQuiz(){const host=qs('#ruleQuiz');if(!host)return;const questions=[{q:'There ___ a lamp on the desk.',ipa:'/ðeər ɪz ə læmp ɒn ðə desk/',ru:'На письменном столе есть лампа.',a:'is'},{q:'There ___ three books on the table.',ipa:'/ðeər ɑː θriː bʊks ɒn ðə ˈteɪbəl/',ru:'На столе есть три книги.',a:'are'}];let i=0;function show(){const x=questions[i%questions.length];host.innerHTML=`<div class="sentence-study"><b>${x.q}</b><span>${x.ipa}</span><em>${x.ru}</em></div><div class="choice-row"><button>is</button><button>are</button></div>`;qsa('button',host).forEach(b=>b.onclick=()=>{if(b.textContent===x.a){reward();character(true,'Great job, Alice! Ты правильно выбрала форму.');i++;setTimeout(show,500)}else{miss();character(false,'No, not right. Один предмет — there is, несколько — there are.')}})}show()}

function initBattle(){const arena=qs('#battleArena');if(!arena)return;let hp=100,score=0;const bar=qs('#monsterHP');const scoreEl=qs('#battleScore');const good=['lamp','bed','window','chair','book','table'];const bad=['лампа','кровать','окно','стул','книга','стол'];function drop(){const useGood=Math.random()>.28;const arr=useGood?good:bad;const w=arr[Math.floor(Math.random()*arr.length)];const el=document.createElement('button');el.className='falling-word';el.textContent=w;el.style.left=(8+Math.random()*78)+'%';el.style.animationDuration=(4+Math.random()*2)+'s';arena.appendChild(el);el.onclick=()=>{if(useGood){score++;hp=Math.max(0,hp-12);reward(5);character(true,'Hit! Great reading, Alice!');}else{miss();character(false,'Это русское слово. Ищи английское!')}scoreEl.textContent=score;bar.style.width=hp+'%';el.remove();if(hp<=0){state.wins++;state.xp+=50;save();qs('#battleWin').classList.remove('hidden');clearInterval(window.battleTimer)}};setTimeout(()=>el.remove(),6500)}window.battleTimer=setInterval(drop,900);for(let k=0;k<4;k++)setTimeout(drop,k*220)}

navActive();paintProgress();initFlashcards();initDrag();initRuleQuiz();initBattle();qsa('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));
